title: Gizzhead.org
tagline: A blog dedicated to all things King Gizzard & The Lizard Wizard
email: admin@gizzhead.org
description: >- # this means to ignore newlines until "baseurl:"
  A blog dedicated to all things King Gizzard & The Lizard Wizard including latest news, historical live show setlists, and bootlegs!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gizzhead.org" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!--fold-->"
logo: "/assets/img/gizzhead.png"
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
     category: "playlist"
    values:
      title: "Playlist of the week"

collections:
  - shows
  - playlists
plugins:
  - jekyll-seo-tag